---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [18]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

df.head()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [28]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [139]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [35]:
def answer_one():
    #return df['Gold'].idxmax()
    return df[df['Gold'] == df['Gold'].max()].index.values[0]
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [40]:
def answer_two():
    return (df['Gold'] - df['Gold.1']).abs().idxmax()
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [43]:
def answer_three():
    countries = df.copy().loc[(df["Gold"]>0) & (df["Gold.1"]>0)]
    countries['gold_diff'] = abs(countries['Gold'] - countries['Gold.1'])
    countries['rel_diff'] = countries['gold_diff'] / (countries['Gold'] + countries['Gold.1'])
    return countries[countries['rel_diff'] == countries['rel_diff'].max()].index.values[0]
answer_three()

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [46]:
def answer_four():
    return df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']
answer_four()

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            923
Austria                              569
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              154
Belgium                              276
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             411
Burundi                                3
Cameroon                              12
Canada                               846
Chile                                 24
China                               1120
Colombia                              29
Costa Rica                             7
Ivory Coast                            2
Croatia                               67
Cuba                                 420
Cyprus                                 2
                                    ...
Spain                                268
Sri Lanka                              4
Sudan                                  2
Suriname                               4
Sweden                              1217
Switzerland                          630
Syria                                  6
Chinese Taipei                        32
Tajikistan                             4
Tanzania                               4
Thailand                              44
Togo                                   1
Tonga                                  2
Trinidad and Tobago                   27
Tunisia                               19
Turkey                               191
Uganda                                14
Ukraine                              220
United Arab Emirates                   3
United States                       5684
Uruguay                               16
Uzbekistan                            38
Venezuela                             18
Vietnam                                4
Virgin Islands                         2
Yugoslavia                           171
Independent Olympic Participants       4
Zambia                                 3
Zimbabwe                              18
Mixed team                            38
Length: 146, dtype: int64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [47]:
census_df = pd.read_csv('census.csv')
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [62]:
def answer_five():
    return census_df.groupby('STNAME').count()
answer_five()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,68,68,68,68,68,68,68,68,68,68,...,68,68,68,68,68,68,68,68,68,68
Alaska,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
Arizona,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
Arkansas,76,76,76,76,76,76,76,76,76,76,...,76,76,76,76,76,76,76,76,76,76
California,59,59,59,59,59,59,59,59,59,59,...,59,59,59,59,59,59,59,59,59,59
Colorado,65,65,65,65,65,65,65,65,65,65,...,65,65,65,65,65,65,65,65,65,65
Connecticut,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
Delaware,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
District of Columbia,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Florida,68,68,68,68,68,68,68,68,68,68,...,68,68,68,68,68,68,68,68,68,68
Georgia,160,160,160,160,160,160,160,160,160,160,...,160,160,160,160,160,160,160,160,160,160
Hawaii,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
Idaho,45,45,45,45,45,45,45,45,45,45,...,45,45,45,45,45,45,45,45,45,45
Illinois,103,103,103,103,103,103,103,103,103,103,...,103,103,103,103,103,103,103,103,103,103
Indiana,93,93,93,93,93,93,93,93,93,93,...,93,93,93,93,93,93,93,93,93,93
Iowa,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
Kansas,106,106,106,106,106,106,106,106,106,106,...,106,106,106,106,106,106,106,106,106,106
Kentucky,121,121,121,121,121,121,121,121,121,121,...,121,121,121,121,121,121,121,121,121,121
Louisiana,65,65,65,65,65,65,65,65,65,65,...,65,65,65,65,65,65,65,65,65,65
Maine,17,17,17,17,17,17,17,17,17,17,...,17,17,17,17,17,17,17,17,17,17
Maryland,25,25,25,25,25,25,25,25,25,25,...,25,25,25,25,25,25,25,25,25,25
Massachusetts,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Michigan,84,84,84,84,84,84,84,84,84,84,...,84,84,84,84,84,84,84,84,84,84
Minnesota,88,88,88,88,88,88,88,88,88,88,...,88,88,88,88,88,88,88,88,88,88
Mississippi,83,83,83,83,83,83,83,83,83,83,...,83,83,83,83,83,83,83,83,83,83
Missouri,116,116,116,116,116,116,116,116,116,116,...,116,116,116,116,116,116,116,116,116,116
Montana,57,57,57,57,57,57,57,57,57,57,...,57,57,57,57,57,57,57,57,57,57
Nebraska,94,94,94,94,94,94,94,94,94,94,...,94,94,94,94,94,94,94,94,94,94
Nevada,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
New Hampshire,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
New Jersey,22,22,22,22,22,22,22,22,22,22,...,22,22,22,22,22,22,22,22,22,22
New Mexico,34,34,34,34,34,34,34,34,34,34,...,34,34,34,34,34,34,34,34,34,34
New York,63,63,63,63,63,63,63,63,63,63,...,63,63,63,63,63,63,63,63,63,63
North Carolina,101,101,101,101,101,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101
North Dakota,54,54,54,54,54,54,54,54,54,54,...,54,54,54,54,54,54,54,54,54,54
Ohio,89,89,89,89,89,89,89,89,89,89,...,89,89,89,89,89,89,89,89,89,89
Oklahoma,78,78,78,78,78,78,78,78,78,78,...,78,78,78,78,78,78,78,78,78,78
Oregon,37,37,37,37,37,37,37,37,37,37,...,37,37,37,37,37,37,37,37,37,37
Pennsylvania,68,68,68,68,68,68,68,68,68,68,...,68,68,68,68,68,68,68,68,68,68
Rhode Island,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
South Carolina,47,47,47,47,47,47,47,47,47,47,...,47,47,47,47,47,47,47,47,47,47
South Dakota,67,67,67,67,67,67,67,67,67,67,...,67,67,67,67,67,67,67,67,67,67
Tennessee,96,96,96,96,96,96,96,96,96,96,...,96,96,96,96,96,96,96,96,96,96
Texas,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
Utah,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
Vermont,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Virginia,134,134,134,134,134,134,134,134,134,134,...,134,134,134,134,134,134,134,134,134,134
Washington,40,40,40,40,40,40,40,40,40,40,...,40,40,40,40,40,40,40,40,40,40
West Virginia,56,56,56,56,56,56,56,56,56,56,...,56,56,56,56,56,56,56,56,56,56
Wisconsin,73,73,73,73,73,73,73,73,73,73,...,73,73,73,73,73,73,73,73,73,73
Wyoming,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [73]:
def answer_six():
    #return list(census_df[census_df['SUMLEV']==50].groupby('STNAME')['CENSUS2010POP'].apply(lambda x: x.nlargest(3).sum()).nlargest(3).index)
    return census_df[census_df['SUMLEV']==50].groupby('STNAME')['CENSUS2010POP'].apply(lambda x: x.nlargest(3))
answer_six()

STNAME
Alabama               37       658466
                      49       412992
                      45       334811
Alaska                71       291826
                      76        97581
                      85        88995
Arizona               106     3817117
                      109      980263
                      110      375770
Arkansas              174      382748
                      118      221339
                      186      203065
California            209     9818605
                      227     3095313
                      220     3010232
Colorado              271      622263
                      266      600158
                      252      572003
Connecticut           315      916829
                      316      894014
                      319      862477
Delaware              325      538479
                      326      197145
                      324      162310
District of Columbia  328      601723
Florida               372     2496435
                      335     1748066
                      379     1320134
Georgia               457      920581
                      464      805321
                               ...
South Dakota          2452     169468
                      2455     100948
                      2444      44828
Tennessee             2549     927644
                      2489     626681
                      2517     432226
Texas                 2667    4092459
                      2623    2368139
                      2786    1809034
Utah                  2839    1029655
                      2846     516564
                      2827     306479
Vermont               2855     156545
                      2862      61642
                      2863      59534
Virginia              2895    1081726
                      2996     437994
                      2939     402002
Washington            3017    1931249
                      3027     795225
                      3031     713335
West Virginia         3060     193063
                      3042     104169
                      3046      96319
Wisconsin             3137     947735
                      3109     488073
                      3164     389891
Wyoming               3180      91738
                      3182      75450
                      3172      46133
Name: CENSUS2010POP, Length: 151, dtype: int64

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [115]:
def answer_seven():
    census_df["Min"] = census_df.loc[census_df["SUMLEV"] == 50, ["POPESTIMATE2010", "POPESTIMATE2011", "POPESTIMATE2012", "POPESTIMATE2013", "POPESTIMATE2014", "POPESTIMATE2015"]].min(axis=1)
    census_df["Max"] = census_df.loc[census_df["SUMLEV"] == 50, ["POPESTIMATE2010", "POPESTIMATE2011", "POPESTIMATE2012", "POPESTIMATE2013", "POPESTIMATE2014", "POPESTIMATE2015"]].max(axis=1)
    census_df["PopGrowth"] = census_df["Max"] - census_df["Min"]
    return census_df.loc[census_df["PopGrowth"] == census_df["PopGrowth"].max(), 'CTYNAME'].values[0]

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [123]:
def answer_eight():
    return census_df.loc[((census_df['REGION']==1) | (census_df['REGION']==2)) & census_df['CTYNAME'].str.startswith('Washington') & (census_df['POPESTIMATE2015']>census_df['POPESTIMATE2014']), ['STNAME', 'CTYNAME']]
answer_eight()

            STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County